config/routes.rb
Rails.application.routes.draw do
  resources :folders
  resources :versions

  root to: "home#index"
  devise_for :users

  # This is a blank app! Pick your first screen, build out the RCAV, and go from there. E.g.:

  # get "/your_first_screen" => "pages#first"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/folder.rb
# == Schema Information
#
# Table name: folders
#
#  id                 :bigint           not null, primary key
#  name               :string
#  versions_count     :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  default_version_id :integer
#
class Folder < ApplicationRecord
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  username               :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/version.rb
# == Schema Information
#
# Table name: versions
#
#  id          :bigint           not null, primary key
#  description :text
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  folder_id   :integer
#  user_id     :integer
#
class Version < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_forgery_protection
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :set_folder, only: %i[ show edit update destroy ]

  # GET /folders or /folders.json
  def index
    @folders = Folder.all
  end

  # GET /folders/1 or /folders/1.json
  def show
  end

  # GET /folders/new
  def new
    @folder = Folder.new
  end

  # GET /folders/1/edit
  def edit
  end

  # POST /folders or /folders.json
  def create
    @folder = Folder.new(folder_params)

    respond_to do |format|
      if @folder.save
        format.html { redirect_to folder_url(@folder), notice: "Folder was successfully created." }
        format.json { render :show, status: :created, location: @folder }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /folders/1 or /folders/1.json
  def update
    respond_to do |format|
      if @folder.update(folder_params)
        format.html { redirect_to folder_url(@folder), notice: "Folder was successfully updated." }
        format.json { render :show, status: :ok, location: @folder }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /folders/1 or /folders/1.json
  def destroy
    @folder.destroy!

    respond_to do |format|
      format.html { redirect_to folders_url, notice: "Folder was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_folder
      @folder = Folder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def folder_params
      params.require(:folder).permit(:name, :default_version_id, :versions_count)
    end
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  before_action :set_version, only: %i[ show edit update destroy ]

  # GET /versions or /versions.json
  def index
    @versions = Version.all
  end

  # GET /versions/1 or /versions/1.json
  def show
  end

  # GET /versions/new
  def new
    @version = Version.new
  end

  # GET /versions/1/edit
  def edit
  end

  # POST /versions or /versions.json
  def create
    @version = Version.new(version_params)

    respond_to do |format|
      if @version.save
        format.html { redirect_to version_url(@version), notice: "Version was successfully created." }
        format.json { render :show, status: :created, location: @version }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @version.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /versions/1 or /versions/1.json
  def update
    respond_to do |format|
      if @version.update(version_params)
        format.html { redirect_to version_url(@version), notice: "Version was successfully updated." }
        format.json { render :show, status: :ok, location: @version }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @version.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /versions/1 or /versions/1.json
  def destroy
    @version.destroy!

    respond_to do |format|
      format.html { redirect_to versions_url, notice: "Version was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_version
      @version = Version.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def version_params
      params.require(:version).permit(:user_id, :name, :description, :folder_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/folders/_folder.html.erb
<div id="<%= dom_id folder %>">
  <p>
    <strong>Name:</strong>
    <%= folder.name %>
  </p>

  <p>
    <strong>Default version:</strong>
    <%= folder.default_version_id %>
  </p>

  <p>
    <strong>Versions count:</strong>
    <%= folder.versions_count %>
  </p>

</div>

app/views/folders/_form.html.erb
<%= form_with(model: folder) do |form| %>
  <% if folder.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(folder.errors.count, "error") %> prohibited this folder from being saved:</h2>

      <ul>
        <% folder.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :default_version_id, style: "display: block" %>
    <%= form.number_field :default_version_id %>
  </div>

  <div>
    <%= form.label :versions_count, style: "display: block" %>
    <%= form.number_field :versions_count %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/folders/edit.html.erb
<h1>Editing folder</h1>

<%= render "form", folder: @folder %>

<br>

<div>
  <%= link_to "Show this folder", @folder %> |
  <%= link_to "Back to folders", folders_path %>
</div>

app/views/folders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Folders</h1>

<div id="folders">
  <% @folders.each do |folder| %>
    <%= render folder %>
    <p>
      <%= link_to "Show this folder", folder %>
    </p>
  <% end %>
</div>

<%= link_to "New folder", new_folder_path %>

app/views/folders/new.html.erb
<h1>New folder</h1>

<%= render "form", folder: @folder %>

<br>

<div>
  <%= link_to "Back to folders", folders_path %>
</div>

app/views/folders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @folder %>

<div>
  <%= link_to "Edit this folder", edit_folder_path(@folder) %> |
  <%= link_to "Back to folders", folders_path %>

  <%= button_to "Destroy this folder", @folder, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Template</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/versions/_form.html.erb
<%= form_with(model: version) do |form| %>
  <% if version.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(version.errors.count, "error") %> prohibited this version from being saved:</h2>

      <ul>
        <% version.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :folder_id, style: "display: block" %>
    <%= form.number_field :folder_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/versions/_version.html.erb
<div id="<%= dom_id version %>">
  <p>
    <strong>User:</strong>
    <%= version.user_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= version.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= version.description %>
  </p>

  <p>
    <strong>Folder:</strong>
    <%= version.folder_id %>
  </p>

</div>

app/views/versions/edit.html.erb
<h1>Editing version</h1>

<%= render "form", version: @version %>

<br>

<div>
  <%= link_to "Show this version", @version %> |
  <%= link_to "Back to versions", versions_path %>
</div>

app/views/versions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Versions</h1>

<div id="versions">
  <% @versions.each do |version| %>
    <%= render version %>
    <p>
      <%= link_to "Show this version", version %>
    </p>
  <% end %>
</div>

<%= link_to "New version", new_version_path %>

app/views/versions/new.html.erb
<h1>New version</h1>

<%= render "form", version: @version %>

<br>

<div>
  <%= link_to "Back to versions", versions_path %>
</div>

app/views/versions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @version %>

<div>
  <%= link_to "Edit this version", edit_version_path(@version) %> |
  <%= link_to "Back to versions", versions_path %>

  <%= button_to "Destroy this version", @version, method: :delete %>
</div>